create table if not exists kpi
(
    id    integer generated by default as identity not null
        constraint kpi_pk
            primary key,
    name  text,
    query text,
    is_deleted boolean default false
);

create table if not exists kpi_variables
(
    id     integer generated by default as identity not null
        constraint kpi_variables_pk
            primary key,
    name   text,
    value  text,
    id_kpi integer not null
        constraint fk_kpi
            references kpi,
    is_deleted boolean default false
);
