create table if not exists eb_cost_types
(
    id      integer generated by default as identity not null
        constraint eb_cost_types_pk
            primary key,
    code text,
    name text
);

create table if not exists reg_eb_cost_types
(
    id      integer generated by default as identity not null
        constraint reg_eb_cost_types_pk
            primary key,
    id_eb_cost_type integer not null
        constraint fk_el_cost_type
            references eb_cost_types,
    id_cost_type integer not null
        constraint fk_cost_type
            references cost_types
);