insert into eb_cost_types(code, name) VALUES ('100', 'Межбюджетные трансферты из федерального бюджета (справочно)');
insert into eb_cost_types(code, name) VALUES ('200', 'Межбюджетные трансферты из ГВБФ (справочно)');
insert into eb_cost_types(code, name) VALUES ('201', 'Сумма соглашений (справочно)');
insert into eb_cost_types(code, name) VALUES ('210', 'Консолидированный бюджет субъекта');
insert into eb_cost_types(code, name) VALUES ('220', 'Бюджет субъекта');
insert into eb_cost_types(code, name) VALUES ('22010', 'Межбюджетные трансферты');
insert into eb_cost_types(code, name) VALUES ('221', 'Федеральный бюджет (межбюджетные трансферты в федеральный бюджет)');
insert into eb_cost_types(code, name) VALUES ('222', 'Бюджеты государственных внебюджетных фондов РФ');
insert into eb_cost_types(code, name) VALUES ('22210', 'Бюджет Пенсионного фонда РФ');
insert into eb_cost_types(code, name) VALUES ('22220', 'Бюджет Фонда социального страхования РФ');
insert into eb_cost_types(code, name) VALUES ('22230', 'Бюджет Федерального фонда обязательного медицинского страхования РФ');
insert into eb_cost_types(code, name) VALUES ('224', 'Бюджеты территориальных государственных внебюджетных фондов (ТФОМС)');
insert into eb_cost_types(code, name) VALUES ('223', 'Местные бюджеты');
insert into eb_cost_types(code, name) VALUES ('225', 'Иные бюджеты субъектов РФ');
insert into eb_cost_types(code, name) VALUES ('240', 'Бюджеты территориальных государственных внебюджетных фондов (ТФОМС)');
insert into eb_cost_types(code, name) VALUES ('24010', 'Межбюджетные трансферты');
insert into eb_cost_types(code, name) VALUES ('24011', 'Бюджеты субъектов РФ');
insert into eb_cost_types(code, name) VALUES ('24012', 'Бюджеты государственных внебюджетных фондов РФ (ТФОМС)');
insert into eb_cost_types(code, name) VALUES ('230', 'Свод бюджетов Муниципальных образований');
insert into eb_cost_types(code, name) VALUES ('231', 'Межбюджетные трансферты в БС');
insert into eb_cost_types(code, name) VALUES ('232', 'Межбюджетные трансферты в МО других субъектов РФ');
insert into eb_cost_types(code, name) VALUES ('250', 'Внебюджетные источники');
insert into eb_cost_types(code, name) VALUES ('251', 'Внебюджетные источники, определенные на федеральном уровне');
insert into eb_cost_types(code, name) VALUES ('252', 'Внебюджетные источники, привлеченные субъектом РФ');