create table if not exists geographic_maps
(
    id         integer generated by default as identity not null
        constraint geographic_maps_pk
            primary key,
    is_deleted boolean default false,
    project_id integer                                  not null
        constraint fk_project
            references projects
);

create table if not exists map_points
(
    id                integer generated by default as identity not null
        constraint map_points_pk
            primary key,
    title             text not null,
    longitude         float,
    latitude          float,
    description       text,
    is_deleted        boolean default false,
    work_package_id   integer
        constraint fk_work_package
            references work_packages,
    project_id        integer                                  not null
        constraint fk_project
            references projects,
    geographic_map_id integer                                  not null
        constraint fk_geographic_map
            references geographic_maps
);
