CREATE TABLE IF NOT EXISTS target_risks (
    id  integer generated by default as identity not null
        constraint target_risks_pk
            primary key,
    target_id   integer not null
        constraint fk_target
            references targets,
    risk_id     integer not null
        constraint fk_risk
            references risks,
    is_solved boolean default false not null,
    solution_date date
);

alter table risks
    add if not exists probability_value integer;

alter table risks
    add if not exists expected_date date;