create table if not exists maps
(
    id         integer generated by default as identity not null
        constraint maps_pk
            primary key,
    is_deleted boolean default false,
    id_project integer                                  not null
        constraint fk_project
            references projects
);

create table if not exists map_points
(
    id              integer generated by default as identity not null
        constraint map_points_pk
            primary key,
    longitude       float,
    latitude        float,
    description     text,
    is_deleted boolean default false,
    id_work_package integer                                  not null
        constraint fk_work_package
            references work_packages,
    id_project      integer                                  not null
        constraint fk_project
            references projects,
    id_map          integer                                  not null
        constraint fk_map
            references maps
);
