//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 11:26:40 AM IRKT 
//


package ru.sibdigital.jopsd.dto.elbudget.execution;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.sibdigital.elbudget.dto.execution package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.sibdigital.elbudget.dto.execution
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resultsexecution }
     * 
     */
    public Resultsexecution createResultsexecution() {
        return new Resultsexecution();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject }
     * 
     */
    public Resultsexecution.RegProject createResultsexecutionRegProject() {
        return new Resultsexecution.RegProject();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.KeyRisks }
     * 
     */
    public Resultsexecution.RegProject.KeyRisks createResultsexecutionRegProjectKeyRisks() {
        return new Resultsexecution.RegProject.KeyRisks();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.KeyRisks.KeyRisk }
     * 
     */
    public Resultsexecution.RegProject.KeyRisks.KeyRisk createResultsexecutionRegProjectKeyRisksKeyRisk() {
        return new Resultsexecution.RegProject.KeyRisks.KeyRisk();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias createResultsexecutionRegProjectPurposeCriterias() {
        return new Resultsexecution.RegProject.PurposeCriterias();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria createResultsexecutionRegProjectPurposeCriteriasPurposeCriteria() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaRisks() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaRisksRisk() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk.ProposedSolutions }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk.ProposedSolutions createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaRisksRiskProposedSolutions() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk.ProposedSolutions();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.ExecutionConfirmingDocuments }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.ExecutionConfirmingDocuments createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaExecutionConfirmingDocuments() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.ExecutionConfirmingDocuments();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.PurposeCriteriaMonthlyExecutions }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.PurposeCriteriaMonthlyExecutions createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaPurposeCriteriaMonthlyExecutions() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.PurposeCriteriaMonthlyExecutions();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results }
     * 
     */
    public Resultsexecution.RegProject.Results createResultsexecutionRegProjectResults() {
        return new Resultsexecution.RegProject.Results();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result }
     * 
     */
    public Resultsexecution.RegProject.Results.Result createResultsexecutionRegProjectResultsResult() {
        return new Resultsexecution.RegProject.Results.Result();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators createResultsexecutionRegProjectResultsResultRpResultIndicators() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicator() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPoints() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPoint() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPointRisks() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPointRisksRisk() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk.ProposedSolutions }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk.ProposedSolutions createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPointRisksRiskProposedSolutions() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk.ProposedSolutions();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.ExecutionConfirmingDocuments }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.ExecutionConfirmingDocuments createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPointExecutionConfirmingDocuments() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.ExecutionConfirmingDocuments();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorRisks() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorRisksRisk() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk.ProposedSolutions }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk.ProposedSolutions createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorRisksRiskProposedSolutions() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk.ProposedSolutions();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.ExecutionConfirmingDocuments }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.ExecutionConfirmingDocuments createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorExecutionConfirmingDocuments() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.ExecutionConfirmingDocuments();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.Risks }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.Risks createResultsexecutionRegProjectResultsResultRisks() {
        return new Resultsexecution.RegProject.Results.Result.Risks();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.Risks.Risk }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.Risks.Risk createResultsexecutionRegProjectResultsResultRisksRisk() {
        return new Resultsexecution.RegProject.Results.Result.Risks.Risk();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.Risks.Risk.ProposedSolutions }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.Risks.Risk.ProposedSolutions createResultsexecutionRegProjectResultsResultRisksRiskProposedSolutions() {
        return new Resultsexecution.RegProject.Results.Result.Risks.Risk.ProposedSolutions();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinsourcetExecutionMonthlyExecutionPlans }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinsourcetExecutionMonthlyExecutionPlans createResultsexecutionRegProjectResultsResultFinsourcetExecutionMonthlyExecutionPlans() {
        return new Resultsexecution.RegProject.Results.Result.FinsourcetExecutionMonthlyExecutionPlans();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinSourceExecutionConsolidatedSubsidies }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinSourceExecutionConsolidatedSubsidies createResultsexecutionRegProjectResultsResultFinSourceExecutionConsolidatedSubsidies() {
        return new Resultsexecution.RegProject.Results.Result.FinSourceExecutionConsolidatedSubsidies();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinancialSources }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinancialSources createResultsexecutionRegProjectResultsResultFinancialSources() {
        return new Resultsexecution.RegProject.Results.Result.FinancialSources();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinancialSources.Risks }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinancialSources.Risks createResultsexecutionRegProjectResultsResultFinancialSourcesRisks() {
        return new Resultsexecution.RegProject.Results.Result.FinancialSources.Risks();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk createResultsexecutionRegProjectResultsResultFinancialSourcesRisksRisk() {
        return new Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk.ProposedSolutions }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk.ProposedSolutions createResultsexecutionRegProjectResultsResultFinancialSourcesRisksRiskProposedSolutions() {
        return new Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk.ProposedSolutions();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.KeyRisks.KeyRisk.BaseRiskProposedSolutions }
     * 
     */
    public Resultsexecution.RegProject.KeyRisks.KeyRisk.BaseRiskProposedSolutions createResultsexecutionRegProjectKeyRisksKeyRiskBaseRiskProposedSolutions() {
        return new Resultsexecution.RegProject.KeyRisks.KeyRisk.BaseRiskProposedSolutions();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.KeyRisks.KeyRisk.RISKCOMMPROJECTDIRS }
     * 
     */
    public Resultsexecution.RegProject.KeyRisks.KeyRisk.RISKCOMMPROJECTDIRS createResultsexecutionRegProjectKeyRisksKeyRiskRISKCOMMPROJECTDIRS() {
        return new Resultsexecution.RegProject.KeyRisks.KeyRisk.RISKCOMMPROJECTDIRS();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk.ProposedSolutions.ProposedSolution }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk.ProposedSolutions.ProposedSolution createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaRisksRiskProposedSolutionsProposedSolution() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.Risks.Risk.ProposedSolutions.ProposedSolution();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.ExecutionConfirmingDocuments.ExecutionConfirmingDocument }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.ExecutionConfirmingDocuments.ExecutionConfirmingDocument createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaExecutionConfirmingDocumentsExecutionConfirmingDocument() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.ExecutionConfirmingDocuments.ExecutionConfirmingDocument();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.PurposeCriteriaMonthlyExecutions.PurposeCriteriaMonthlyExecution }
     * 
     */
    public Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.PurposeCriteriaMonthlyExecutions.PurposeCriteriaMonthlyExecution createResultsexecutionRegProjectPurposeCriteriasPurposeCriteriaPurposeCriteriaMonthlyExecutionsPurposeCriteriaMonthlyExecution() {
        return new Resultsexecution.RegProject.PurposeCriterias.PurposeCriteria.PurposeCriteriaMonthlyExecutions.PurposeCriteriaMonthlyExecution();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.DocCheckPoints }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.DocCheckPoints createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPointDocCheckPoints() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.DocCheckPoints();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk.ProposedSolutions.ProposedSolution }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk.ProposedSolutions.ProposedSolution createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPointRisksRiskProposedSolutionsProposedSolution() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.Risks.Risk.ProposedSolutions.ProposedSolution();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.ExecutionConfirmingDocuments.ExecutionConfirmingDocument }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.ExecutionConfirmingDocuments.ExecutionConfirmingDocument createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorCheckPointsCheckPointExecutionConfirmingDocumentsExecutionConfirmingDocument() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.CheckPoints.CheckPoint.ExecutionConfirmingDocuments.ExecutionConfirmingDocument();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk.ProposedSolutions.ProposedSolution }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk.ProposedSolutions.ProposedSolution createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorRisksRiskProposedSolutionsProposedSolution() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.Risks.Risk.ProposedSolutions.ProposedSolution();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.ExecutionConfirmingDocuments.ExecutionConfirmingDocument }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.ExecutionConfirmingDocuments.ExecutionConfirmingDocument createResultsexecutionRegProjectResultsResultRpResultIndicatorsRpResultIndicatorExecutionConfirmingDocumentsExecutionConfirmingDocument() {
        return new Resultsexecution.RegProject.Results.Result.RpResultIndicators.RpResultIndicator.ExecutionConfirmingDocuments.ExecutionConfirmingDocument();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.Risks.Risk.ProposedSolutions.ProposedSolution }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.Risks.Risk.ProposedSolutions.ProposedSolution createResultsexecutionRegProjectResultsResultRisksRiskProposedSolutionsProposedSolution() {
        return new Resultsexecution.RegProject.Results.Result.Risks.Risk.ProposedSolutions.ProposedSolution();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinsourcetExecutionMonthlyExecutionPlans.FinsourcetExecutionMonthlyExecutionPlan }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinsourcetExecutionMonthlyExecutionPlans.FinsourcetExecutionMonthlyExecutionPlan createResultsexecutionRegProjectResultsResultFinsourcetExecutionMonthlyExecutionPlansFinsourcetExecutionMonthlyExecutionPlan() {
        return new Resultsexecution.RegProject.Results.Result.FinsourcetExecutionMonthlyExecutionPlans.FinsourcetExecutionMonthlyExecutionPlan();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinSourceExecutionConsolidatedSubsidies.FinSourceExecutionConsolidatedSubsidy }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinSourceExecutionConsolidatedSubsidies.FinSourceExecutionConsolidatedSubsidy createResultsexecutionRegProjectResultsResultFinSourceExecutionConsolidatedSubsidiesFinSourceExecutionConsolidatedSubsidy() {
        return new Resultsexecution.RegProject.Results.Result.FinSourceExecutionConsolidatedSubsidies.FinSourceExecutionConsolidatedSubsidy();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinancialSources.FinancialSource }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinancialSources.FinancialSource createResultsexecutionRegProjectResultsResultFinancialSourcesFinancialSource() {
        return new Resultsexecution.RegProject.Results.Result.FinancialSources.FinancialSource();
    }

    /**
     * Create an instance of {@link Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk.ProposedSolutions.ProposedSolution }
     * 
     */
    public Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk.ProposedSolutions.ProposedSolution createResultsexecutionRegProjectResultsResultFinancialSourcesRisksRiskProposedSolutionsProposedSolution() {
        return new Resultsexecution.RegProject.Results.Result.FinancialSources.Risks.Risk.ProposedSolutions.ProposedSolution();
    }

}
